# tasks file for roles/node_exporter
---
- name: create node_exporter system group
  group:
    name: node_exporter
    system: true
    state: present

- name: node_exporter User add
  user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false

- block:
    - name: download node_exporter package to localhost
      become: false
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    - name: unpack node_exporter binaries
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: copy node_exporter and promtool binaries files
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/{{ item }}"
        dest: "{{ node_exporter_binary_install_dir }}/{{ item }}"
        mode: 0755
        owner: root
        group: root
        remote_src: yes
      with_items:
        - node_exporter

- name: Configuration systemd Files for node_exporter
  template:
    src: node_exporter.systemd.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node_exporter

- name: reload for node_exporter
  systemd:
    name: node_exporter
    enabled: true
    state: started
